{   yaw_Kd: 10.,
    yaw_Ki: .1,
    yaw_Kp: 15.0,
    yaw_max: 20,
    yaw_imax: 10,
    surge_Kd: 2.0,
    surge_Ki: 0.1,
    surge_Kp: 4.0,
    surge_max: 80,
    surge_imax: 40,
    sway_Kd: 2.0,
    sway_Ki: 0.1,
    sway_Kp: 4.0,
    sway_max: 20,
    sway_imax: 10}
