{   yaw_Kd: 30.,
    yaw_Ki: 10.,
    yaw_Kp: 50.0,
    yaw_max: 20,
    yaw_imax: 10,
    surge_Kd: 5.0,
    surge_Ki: 1,
    surge_Kp: 20.0,
    surge_max: 20,
    surge_imax: 10,
    sway_Kd: 20.0,
    sway_Ki: 1,
    sway_Kp: 5.0,
    sway_max: 20,
    sway_imax: 10}
