{angular_x_Kd: 0.0, angular_x_Ki: 0.0, angular_x_Kp: 0.0, angular_y_Kd: 0.0, angular_y_Ki: 0.0,
  angular_y_Kp: 0.0, angular_z_Kd: 2.0, angular_z_Ki: 0.1, angular_z_Kp: 1.0,
  linear_x_Kd: 2.0, linear_x_Ki: 0.01, linear_x_Kp: 2.0, linear_y_Kd: 2.0, linear_y_Ki: 0.01,
  linear_y_Kp: 1.0, linear_z_Kd: 0.0, linear_z_Ki: 0.0, linear_z_Kp: 0.0}
