# Service to request a new plan from the mission planner

int8 fault # fault type
int8[] completed # list of completed tasks
int8[] skipped # list of skipped tasks
float64 burned # value measured from energy/aggregator
float64[] cost_mu # list of completed task energy measurements
float64[] cost_std # list of completed task energy standard deviations
float64 northing # Northing (utm) of vehicle's current position
float64 easting  # Easting (utm) of vehicle's current position
float64 latitude # Latitude of vehicle's current position.
float64 longitude #Longitude of vehicle's current position.
---
bool success # letting the vehicle know to listen for plan
string message # status update from mission planner.
